name: localin
description: Localin app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.4
  dotted_border: ^1.0.4
  intl: ^0.16.0
  dio: ^3.0.7
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.15.3
  google_maps_flutter: ^0.5.21+15
  google_sign_in: ^4.1.1
  provider: ^3.2.0
  shared_preferences: ^0.5.6
  image_picker: ^0.6.2+3
  permission_handler: ^4.0.0
  geolocator: ^5.1.5
  video_player: ^0.10.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
          weight: 400
        - asset: fonts/OpenSans-Italic.ttf
          style: italic