name: localin
description: Localin app

version: 1.7.0+170

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^5.0.2
  intl: ^0.19.0
  dio: ^5.6.0
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  html: ^0.15.4
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.2
  flutter_image_compress: ^2.3.0
  auto_size_text: ^3.0.0
  flutter_native_timezone: ^2.0.0
  superellipse_shape: ^0.2.0
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  oktoast: ^3.4.0
  webview_flutter: ^4.9.0
  get_it: ^7.7.0
  photo_manager: ^3.2.3
  equatable: ^2.0.5
  sembast: ^3.7.3+2
  path_provider: ^2.1.4
  add_2_calendar: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  table_calendar: ^3.1.2
  scroll_snap_list: ^0.9.1
  flutter_xlider: ^3.5.0
  scroll_to_index: ^3.0.1
  readmore: ^3.0.0
  url_launcher: ^6.3.0
  youtube_player_flutter: ^9.0.3
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - map_style.txt
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
          weight: 400
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
    - family: SfProText
      fonts:
        - asset: fonts/SFProText-Regular.ttf
        - asset: fonts/SFProText-Medium.ttf
          weight: 400
        - asset: fonts/SFProText-SemiBold.ttf
          weight: 600
    - family: Rodina
      fonts:
        - asset: fonts/Rodina.ttf