name: localin
description: Localin app

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.4
  dotted_border: ^1.0.4
  intl: ^0.16.0
  dio: any
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.15.3
  google_maps_flutter: ^0.5.21+15
  google_sign_in: ^4.1.1
  provider: ^3.2.0
  shared_preferences: ^0.5.6
  image_picker: ^0.6.2+3
  permission_handler: ^4.0.0
  geolocator: ^5.1.5
  video_player: ^0.10.2+1
  geocoder: ^0.2.1
  flutter_pagewise: ^1.2.3
  cached_network_image: ^2.0.0
  flutter_webview_plugin: ^0.3.10+1
  android_intent: ^0.3.5
  photo_view: ^0.9.1
  html: ^0.14.0+3
  carousel_slider: ^1.4.1
  esys_flutter_share: ^1.0.2
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.1.5+1
  flutter_image_compress: ^0.6.5+1
  auto_size_text: ^2.1.0
  firebase_crashlytics: ^0.1.2+5
  flutter_native_timezone: ^1.0.4
  superellipse_shape: ^0.1.5
  flutter_styled_toast: ^1.2.1
  flutter_svg: ^0.17.4
  flutter_dash: ^0.0.1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+5
  async: ^2.4.0
  oktoast: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
          weight: 400
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
    - family: SfProText
      fonts:
        - asset: fonts/SFProText-Regular.ttf
        - asset: fonts/SFProText-Medium.ttf
          weight: 400
        - asset: fonts/SFProText-SemiBold.ttf
          weight: 600
    - family: Rodina
      fonts:
        - asset: fonts/Rodina.ttf